modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="forest"
version="1.0.0.2"
displayName="Forest X Reborn"
credits="Created by MagicalAlexey"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forest-x-reborn"
updateJSONURL="https://raw.githubusercontent.com/MagicalAlexey/Forest-X-Java-Edition/main/update.json"
logoFile="logo.png"
authors="MagicalAlexey"
description='''
 The revival of the legendary Forest X Second Edition addon, but only for Minecraft Java Edition.
'''

[[dependencies.forest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




